=== zamek42/flight/data/flights.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
         elementFormDefault="qualified"
        attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        
	<xs:element name="airlines">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="airline" minOccurs="1" maxOccurs="unbounded"/>			
			</xs:sequence>
		</xs:complexType>
	</xs:element>        
	
	<xs:element name="airline">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="flights" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="flights">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="flight" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="flight">
		<xs:complexType>
			<xs:attribute name="flightId" type="xs:ID" use="required"/>
			<xs:attribute name="from" type="xs:string" use="required"/>
			<xs:attribute name="to" type="xs:string" use="required"/>
			<xs:attribute name="distance" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="during" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== zamek42/flight/data/flights.xml
<?xml version="1.0" encoding="utf-8"?>

<airlines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./flights.xsd">

	<airline name="KLM">
		<flights>
			<flight flightId="KLM1" from="Budapest" to="Moscow" distance="1565" during="03:30:00" departure="00:00:00"/>
			<flight flightId="KLM1R" from="Moscow" to="Budapest" distance="1565" during="03:30:00" departure="08:00:00"/>
			
			<flight flightId="KLM2" from="Budapest" to="Kiev" distance="896" during="01:48:00"  departure="00:00:00"/>
			<flight flightId="KLM2R" from="Kiev" to="Budapest" distance="896" during="01:48:00"  departure="06:00:00"/>
			
			<flight flightId="KLM3" from="Budapest" to="Cluj-Napoca" distance="350" during="00:42:00"  departure="01:00:00"/>
			<flight flightId="KLM3R" from="Cluj-Napoca" to="Budapest" distance="350" during="00:42:00"  departure="07:00:00"/>
			
			<flight flightId="KLM4" from="Budapest" to="Bucharest" distance="645" during="01:18:00"  departure="01:00:00"/>
			<flight flightId="KLM4R" from="Bucharest" to="Budapest" distance="645" during="01:18:00"  departure="07:00:00"/>
			
			<flight flightId="KLM5" from="Budapest" to="Istanbul" distance="1073" during="02:09:00"  departure="02:00:00"/>
			<flight flightId="KLM5R" from="Istanbul" to="Budapest" distance="1073" during="02:09:00"  departure="09:00:00"/>

			<flight flightId="KLM6" from="Budapest" to="Bari" distance="739" during="01:30:00"  departure="02:00:00"/>
			<flight flightId="KLM6R" from="Bari" to="Budapest" distance="739" during="01:30:00"  departure="09:00:00"/>

			<flight flightId="KLM7" from="Budapest" to="Rome" distance="821" during="01:36:00"  departure="03:00:00"/>
			<flight flightId="KLM7R" from="Rome" to="Budapest" distance="821" during="01:36:00"  departure="15:00:00"/>

			<flight flightId="KLM8" from="Budapest" to="Milan" distance="791" during="01:30:00"  departure="03:00:00"/>
			<flight flightId="KLM8R" from="Milan" to="Budapest" distance="791" during="01:30:00"  departure="11:00:00"/>

			<flight flightId="KLM9" from="Budapest" to="Barcelona" distance="1502" during="03:00:00"  departure="04:00:00"/>
			<flight flightId="KLM9R" from="Barcelona" to="Budapest" distance="1502" during="03:00:00"  departure="11:00:00"/>

			<flight flightId="KLM10" from="Budapest" to="Madrid" distance="1974" during="03:54:00"  departure="04:00:00"/>
			<flight flightId="KLM10R" from="Madrid" to="Budapest" distance="1974" during="03:54:00"  departure="16:00:00"/>

			<flight flightId="KLM11" from="Budapest" to="Paris" distance="1241" during="02:24:00"  departure="05:00:00"/>
			<flight flightId="KLM11R" from="Paris" to="Budapest" distance="1241" during="02:24:00"  departure="17:00:00"/>

			<flight flightId="KLM12" from="Budapest" to="Vienna" distance="220" during="00:25:00"  departure="05:00:00"/>
			<flight flightId="KLM12R" from="Vienna" to="Budapest" distance="220" during="00:25:00"  departure="17:00:00"/>

			<flight flightId="KLM13" from="Budapest" to="Frankfurt" distance="813" during="01:36:00"  departure="06:00:00"/>
			<flight flightId="KLM13R" from="Frankfurt" to="Budapest" distance="813" during="01:36:00"  departure="18:00:00"/>

			<flight flightId="KLM14" from="Budapest" to="Berlin" distance="678" during="01:24:00"  departure="06:00:00"/>
			<flight flightId="KLM14R" from="Berlin" to="Budapest" distance="678" during="01:24:00"  departure="18:00:00"/>

			<flight flightId="KLM15" from="Budapest" to="Amsterdam" distance="710" during="01:25:00"  departure="07:00:00"/>
			<flight flightId="KLM15R" from="Amsterdam" to="Budapest" distance="710" during="01:25:00"  departure="19:00:00"/>

			<flight flightId="KLM16" from="Budapest" to="London" distance="1450" during="02:54:00"  departure="07:00:00"/>
			<flight flightId="KLM16R" from="London" to="Budapest" distance="1450" during="02:54:00"  departure="19:00:00"/>

			<flight flightId="KLM17" from="Budapest" to="Dublin" distance="1897" during="03:45:00"  departure="08:00:00"/>
			<flight flightId="KLM17R" from="Dublin" to="Budapest" distance="1897" during="03:45:00"  departure="20:00:00"/>

			<flight flightId="KLM18" from="London" to="Miami" distance="7133" during="14:12:00"  departure="08:00:00"/>
			<flight flightId="KLM18R" from="Miami" to="London" distance="7133" during="14:12:00"  departure="20:00:00"/>

			<flight flightId="KLM19" from="London" to="New York" distance="5580" during="11:10:00"  departure="09:00:00"/>
			<flight flightId="KLM19R" from="New York" to="London" distance="5580" during="11:10:00"  departure="21:00:00"/>
			
			<flight flightId="KLM20" from="New York" to="Las Vegas" distance="3571" during="07:10:00"  departure="09:00:00"/>
			<flight flightId="KLM20R" from="Las Vegas" to="New York" distance="3571" during="07:10:00"  departure="21:00:00"/>

			<flight flightId="KLM21" from="New York" to="Phoenix" distance="3450" during="06:54:00"  departure="10:00:00"/>
			<flight flightId="KLM21R" from="Phoenix" to="New York" distance="3450" during="06:54:00"  departure="22:00:00"/>
			
			<flight flightId="KLM22" from="New York" to="Atlanta" distance="1200" during="02:24:00"  departure="10:00:00"/>
			<flight flightId="KLM22R" from="Atlanta" to="New York" distance="1200" during="02:24:00"  departure="22:00:00"/>
			
			<flight flightId="KLM23" from="New York" to="Houston" distance="2259" during="04:35:00"  departure="11:00:00"/>
			<flight flightId="KLM23R" from="Houston" to="New York" distance="2259" during="04:35:00"  departure="23:00:00"/>

			<flight flightId="KLM24" from="New York" to="Denver" distance="2605" during="05:12:00"  departure="11:00:00"/>
			<flight flightId="KLM24R" from="Denver" to="New York" distance="2605" during="05:12:00"  departure="23:00:00"/>

			<flight flightId="KLM25" from="New York" to="Los Angeles" distance="3927" during="07:52:00"  departure="12:00:00"/>
			<flight flightId="KLM25R" from="Los Angeles" to="New York" distance="3927" during="07:52:00"  departure="19:00:00"/>

			<flight flightId="KLM26" from="New York" to="San Francisco" distance="4130"	during="08:18:00"  departure="12:00:00" />
			<flight flightId="KLM26R" from="San Francisco" to="New York" distance="4130" during="08:18:00"  departure="20:00:00" />

			<flight flightId="KLM27" from="New York" to="Miami" distance="1764" during="03:30:00"  departure="13:00:00"/>
			<flight flightId="KLM27R" from="Miami" to="New York" distance="1764" during="03:30:00"  departure="21:00:00"/>
		</flights>
	</airline>

	<airline name="WizzAir">
		<flights>
			<flight flightId="WIZZ1" from="Budapest" to="Baku" distance="2571" during="05:12:00"  departure="00:00:00"/>
			<flight flightId="WIZZR" from="Baku" to="Budapest" distance="2571" during="05:12:00"  departure="09:00:00"/>
			
			<flight flightId="WIZZ2" from="Budapest" to="Tirana" distance="700" during="01:24:00" departure="00:00:00"/>
			<flight flightId="WIZZ2R" from="Tirana" to="Budapest" distance="700" during="01:24:00" departure="10:00:00"/>

			<flight flightId="WIZZ3" from="Budapest" to="Brussels" distance="1120" during="02:15:00" departure="01:00:00"/>
			<flight flightId="WIZZ3R" from="Brussels" to="Budapest" distance="1120" during="02:15:00" departure="10:00:00"/>
			
			<flight flightId="WIZZ4" from="Budapest" to="Sarajevo" distance="418" during="00:48:00" departure="01:00:00"/>
			<flight flightId="WIZZ4R" from="Sarajevo" to="Budapest" distance="418" during="00:48:00" departure="11:00:00"/>

			<flight flightId="WIZZ5" from="Budapest" to="Burgas" distance="864" during="01:45:00" departure="02:00:00"/>
			<flight flightId="WIZZ5R" from="Burgas" to="Budapest" distance="864" during="01:45:00" departure="11:00:00"/>

			<flight flightId="WIZZ6" from="Budapest" to="Larnaka" distance="1857" during="03:45:00" departure="02:00:00"/>
			<flight flightId="WIZZ6R" from="Larnaka" to="Budapest" distance="1857" during="03:45:00" departure="12:00:00"/>

			<flight flightId="WIZZ7" from="Budapest" to="Dubai" distance="4028" during="08:06:00" departure="03:00:00"/>
			<flight flightId="WIZZ7R" from="Dubai" to="Budapest" distance="4028" during="08:06:00" departure="12:00:00"/>

			<flight flightId="WIZZ8" from="Budapest" to="Bordeaux" distance="1542" during="03:06:00" departure="03:00:00"/>
			<flight flightId="WIZZ8R" from="Bordeaux" to="Budapest" distance="1542" during="03:06:00" departure="13:00:00"/>

			<flight flightId="WIZZ9" from="Budapest" to="Athens" distance="1131" during="02:18:00" departure="04:00:00"/>
			<flight flightId="WIZZ9R" from="Athens" to="Budapest" distance="1131" during="02:18:00" departure="13:00:00"/>

			<flight flightId="WIZZ10" from="Budapest" to="Rodos" distance="1452" during="02:54:00" departure="04:00:00"/>
			<flight flightId="WIZZ10R" from="Rodos" to="Budapest" distance="1452" during="02:54:00" departure="14:00:00"/>

			<flight flightId="WIZZ11" from="Budapest" to="Thessaloniki" distance="819" during="01:42:00" departure="05:00:00"/>
			<flight flightId="WIZZ1R" from="Thessaloniki" to="Budapest" distance="819" during="01:42:00" departure="14:00:00"/>

			<flight flightId="WIZZ12" from="Budapest" to="Eindhoven" distance="1066" during="02:10:00" departure="05:00:00"/>
			<flight flightId="WIZZ12R" from="Eindhoven" to="Budapest" distance="1066" during="02:10:00" departure="15:00:00"/>

			<flight flightId="WIZZ13" from="Budapest" to="Reykjavík" distance="3065" during="06:10:00" departure="06:00:00"/>
			<flight flightId="WIZZ13R" from="Reykjavík" to="Budapest" distance="3065" during="06:10:00" departure="15:00:00"/>

			<flight flightId="WIZZ14" from="Budapest" to="Tel Aviv-Yafo" distance="2167" during="04:20:00" departure="07:00:00"/>
			<flight flightId="WIZZ14R" from="Tel Aviv-Yafo" to="Budapest" distance="2167" during="04:20:00" departure="16:00:00"/>

			<flight flightId="WIZZ15" from="Budapest" to="Pristina" distance="558" during="01:06:00" departure="07:00:00"/>
			<flight flightId="WIZZ15R" from="Pristina" to="Budapest" distance="558" during="01:06:00" departure="16:00:00"/>
